//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoParts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoParts()
        {
            this.Orders = new HashSet<Orders>();
            this.Sales = new HashSet<Sales>();
            this.Supply = new HashSet<Supply>();
        }
    
        public int IdAutoPart { get; set; }
        public string NameAutoParts { get; set; }
        public int IdAutoPartsСategory { get; set; }
        public string DescriptionAutoPart { get; set; }
        public int InStock { get; set; }
        public decimal Price { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual AutoPartsСategory AutoPartsСategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply> Supply { get; set; }
    }
}
